-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY') AS "YEAR"
      , TO_CHAR(SALES_DATE, 'MM') AS "MONTH"
      , GENDER
      , COUNT(DISTINCT(A.USER_ID))
  FROM USER_INFO A, ONLINE_SALE B
 WHERE A.USER_ID = B.USER_ID
   AND GENDER IS NOT NULL
 GROUP BY TO_CHAR(SALES_DATE, 'YYYY')
          , TO_CHAR(SALES_DATE, 'MM')
          , GENDER
 ORDER BY YEAR, MONTH, GENDER