-- 코드를 입력하세요
SELECT FLAVOR
  FROM (
        SELECT T2.FLAVOR, SUM(T2.TOTAL_ORDER), SUM(T1.TOTAL_ORDER),
               (SUM(T2.TOTAL_ORDER) + SUM(T1.TOTAL_ORDER)) AS "TOTAL_SUM"
          FROM FIRST_HALF T1 RIGHT OUTER JOIN JULY T2
            ON (T1.FLAVOR = T2.FLAVOR)
         GROUP BY T2.FLAVOR
         ORDER BY TOTAL_SUM DESC
      )
WHERE ROWNUM < 4