-- 코드를 입력하세요
-- outer join
SELECT NAME, DATETIME
FROM(SELECT T1.NAME, T1.DATETIME
  FROM ANIMAL_INS T1 LEFT OUTER JOIN ANIMAL_OUTS T2
   ON T1.ANIMAL_ID = T2.ANIMAL_ID
 WHERE T2.DATETIME IS NULL
 ORDER BY T1.DATETIME)
 WHERE ROWNUM <= 3
 
 
-- SELECT NAME, DATETIME
-- FROM(SELECT A.NAME, A.DATETIME
--     FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B
--      ON(A.ANIMAL_ID=B.ANIMAL_ID)
--     WHERE B.ANIMAL_ID IS NULL
-- ORDER BY DATETIME
--     )
-- WHERE ROWNUM <=3