-- 코드를 입력하세요
SELECT T1.PRODUCT_ID, T1.PRODUCT_NAME,
       SUM(T1.PRICE*T2.AMOUNT) AS "TOTAL_SALES"
  FROM FOOD_PRODUCT T1 INNER JOIN FOOD_ORDER T2
    ON (T1.PRODUCT_ID = T2.PRODUCT_ID)
 WHERE TO_CHAR(T2.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
 GROUP BY T1.PRODUCT_ID, T1.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC

-- SELECT T1.PRODUCT_ID, SUM(T2.AMOUNT)
--   FROM FOOD_PRODUCT T1 INNER JOIN FOOD_ORDER T2
--     ON (T1.PRODUCT_ID = T2.PRODUCT_ID)
--  WHERE TO_CHAR(T2.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
--  GROUP BY T1.PRODUCT_ID

-- SELECT X.PRODUCT_ID, S.PRODUCT_NAME,X.TOTAL_SALES
--   FROM (SELECT A.PRODUCT_ID,SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
--           FROM FOOD_PRODUCT A, FOOD_ORDER B
--          WHERE A.PRODUCT_ID = B.PRODUCT_ID
--            AND TO_CHAR(B.PRODUCE_DATE,'YYYYMM') = '202205' 
--        GROUP BY A.PRODUCT_ID
--        ORDER BY SUM(A.PRICE*B.AMOUNT) DESC, A.PRODUCT_ID ASC) X, FOOD_PRODUCT S
--   WHERE X.PRODUCT_ID = S.PRODUCT_ID