-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
  FROM PATIENT P, DOCTOR D, APPOINTMENT A
 WHERE P.PT_NO = A.PT_NO
   AND A.MCDP_CD = D.MCDP_CD
   AND D.DR_ID = A.MDDR_ID
   
   AND A.APNT_CNCL_YN = 'N'
   AND A.MCDP_CD = 'CS'
   AND TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
 ORDER BY A.APNT_YMD
 
--  SELECT C.APNT_NO,A.PT_NAME, A.PT_NO, C.MCDP_CD, B.DR_NAME, C.APNT_YMD
--   FROM PATIENT A, DOCTOR B, APPOINTMENT C
--  WHERE A.PT_NO = C.PT_NO
--    AND B.MCDP_CD = C.MCDP_CD
--    AND B.DR_ID = C.MDDR_ID
--    --AND APNT_CNCL_YMD IS NULL 
--    AND C.APNT_CNCL_YN ='N'
--    AND C.MCDP_CD = 'CS'
--    AND TO_CHAR(C.APNT_YMD,'YYYYMMDD') = '20220413'
-- ORDER BY C.APNT_YMD