-- 코드를 입력하세요
SELECT T1.REST_ID, T1.REST_NAME, T1.FOOD_TYPE, T1.FAVORITES,
       T1.ADDRESS, ROUND(AVG(T2.REVIEW_SCORE),2) AS AVG_SCORE
  FROM REST_INFO T1 INNER JOIN REST_REVIEW T2
    ON (T1.REST_ID = T2.REST_ID)
 WHERE SUBSTR(T1.ADDRESS,1,2) = '서울'
 GROUP BY T1.REST_ID, T1.REST_NAME, T1.FOOD_TYPE, T1.FAVORITES,
          T1.ADDRESS
 ORDER BY AVG_SCORE DESC, FAVORITES DESC